/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueryImport } from './routes/query'

// Create Virtual Routes

const StateLazyImport = createFileRoute('/state')()
const FormLazyImport = createFileRoute('/form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StateLazyRoute = StateLazyImport.update({
  id: '/state',
  path: '/state',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/state.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const QueryRoute = QueryImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/state': {
      id: '/state'
      path: '/state'
      fullPath: '/state'
      preLoaderRoute: typeof StateLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/query': typeof QueryRoute
  '/form': typeof FormLazyRoute
  '/state': typeof StateLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/query': typeof QueryRoute
  '/form': typeof FormLazyRoute
  '/state': typeof StateLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/query': typeof QueryRoute
  '/form': typeof FormLazyRoute
  '/state': typeof StateLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/query' | '/form' | '/state'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/query' | '/form' | '/state'
  id: '__root__' | '/' | '/query' | '/form' | '/state'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  QueryRoute: typeof QueryRoute
  FormLazyRoute: typeof FormLazyRoute
  StateLazyRoute: typeof StateLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  QueryRoute: QueryRoute,
  FormLazyRoute: FormLazyRoute,
  StateLazyRoute: StateLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/query",
        "/form",
        "/state"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/query": {
      "filePath": "query.tsx"
    },
    "/form": {
      "filePath": "form.lazy.tsx"
    },
    "/state": {
      "filePath": "state.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
